# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartakiada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
